storePassword=Sweety@1998
keyPassword=Sweety@1998
keyAlias=nookienation_tictactoe_cal-release
storeFile=/Users/sweetyrawat/Desktop/github uploaded/nookienation_tictactoe_calc/nookienation_tictactoe_cal-release-key.jks
